// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAIjFBrqqLXdJhZEKu_vKISFPx35SD5aR4",
    appId: "1:925143526892:web:611b4ab623aaeb662464c9",
    messagingSenderId: "925143526892",
    projectId: "financeiro-4009f",
    authDomain: "financeiro-4009f.firebaseapp.com",
    storageBucket: "financeiro-4009f.firebasestorage.app",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyAIjFBrqqLXdJhZEKu_vKISFPx35SD5aR4",
    appId: "1:925143526892:web:611b4ab623aaeb662464c9",
    messagingSenderId: "925143526892",
    projectId: "financeiro-4009f",
    storageBucket: "financeiro-4009f.firebasestorage.app",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyAIjFBrqqLXdJhZEKu_vKISFPx35SD5aR4",
    appId: "1:925143526892:web:611b4ab623aaeb662464c9",
    messagingSenderId: "925143526892",
    projectId: "financeiro-4009f",
    storageBucket: "financeiro-4009f.firebasestorage.app",
    iosBundleId: 're',
  );
}
